Corrected OS terminology
Konsentus/localenv-builder pull request #8
Opened 2020-11-02 09:12 UTC by chrishunter-konsentus

2020-11-02 09:31 UTC, davidjdixon requested changes
at the moment, this is missing the actual use of `which_os` so this would case empty strings to be printed

2020-11-02 09:31 UTC, davidjdixon commented on scripts/helpers
> +    unameOut="$(uname -s)"
use `local x` to ensure the var isn't exposed globally

2020-11-03 07:57 UTC, chrishunter-konsentus commented on scripts/helpers
> +    unameOut="$(uname -s)"
Good thought. Added.

2020-11-03 07:58 UTC, chrishunter-konsentus commented on scripts/helpers
> +    unameOut="$(uname -s)"
Added missing `which_os`. This will teach me to split up a commit.

![](https://media2.giphy.com/media/XsUtdIeJ0MWMo/200.gif)

2020-11-03 12:31 UTC, davidjdixon requested changes
... might be easier to push all changes instead of trying to break them apart as its leaving portions missing.

2020-11-03 12:31 UTC, davidjdixon commented on scripts/clean
> -echo -n "Enter Your MacOS "
still missing use of which_os for the clean script 🙁

2020-11-03 15:30 UTC, chrishunter-konsentus commented on scripts/clean
> -echo -n "Enter Your MacOS "
@davidjdixon I think you commented on the old code rather than the change

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/59562077/98005811-62605d00-1de9-11eb-9b07-172688347530.png">

2020-11-05 08:10 UTC, chrishunter-konsentus commented
Closing for the moment

2020-11-05 08:10 UTC, closed without merging